name: Release Framework

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Version of the Release


jobs:
  create:
    name: Create XCFramework
    runs-on: macos-latest

    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Archive Different Environments
        run: |
          xcodebuild archive -scheme "chainsaw" -configuration Release -destination 'generic/platform=iOS Simulator' -archivePath './build/chainsaw.framework-iphoneos.xcarchive'
          xcodebuild archive -scheme "chainsaw" -configuration Release -destination 'generic/platform=iOS' -archivePath './build/chainsaw.framework-iphonesimulator.xcarchive'
          xcodebuild archive -scheme "chainsaw" -configuration Release -destination 'platform=macOS,arch=x86_64,variant=Mac Catalyst' -archivePath './build/chainsaw.framework-catalyst.xcarchive'
          
      - name: Generate XCFramework
        run: >
          xcodebuild -create-xcframework
          -framework './build/chainsaw.framework-iphonesimulator.xcarchive/Products/Library/Frameworks/chainsaw.framework'
          -framework './build/chainsaw.framework-iphoneos.xcarchive/Products/Library/Frameworks/chainsaw.framework'
          -framework './build/chainsaw.framework-catalyst.xcarchive/Products/Library/Frameworks/chainsaw.framework'
          -output './build/chainsaw.xcframework'
      
      - name: Compress XCFramework
        run: |
          ditto -c -k --sequesterRsrc --keepParent ./build/chainsaw.xcframework ./build/chainsaw.xcframework.zip
          
      ## This can definitely be improved to use pattern matching instead of the entire line
      - name: Update Package File
        run: |
          CHECKSUM=$(swift package compute-checksum ./build/chainsaw.xcframework.zip)
          CHECKSUMLINE="      checksum: \"${CHECKSUM}\"" 
          URL="      url: \"https:\/\/github.com\/Zamo22\/fantastic-chainsaw\/releases\/download\/${{ github.event.inputs.version }}\/chainsaw.xcframework.zip\","
          sed -i '' "17s/.*/$URL/" "./Package.swift"
          sed -i '' "18s/.*/$CHECKSUMLINE/" "./Package.swift"
          
          
      - name: Commit package file changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Zamo22
          author_email: zmoola22@gmail.com
          message: 'Updating Package file for release'
          add: 'Package.swift'
          tag: '${{ github.event.inputs.version }}'

          
      - name: Upload Compressed Framework Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: chainsaw.xcframework.zip
          path: ./build/chainsaw.xcframework.zip

          
  release:
    name: Create Release
    runs-on: macos-latest
    needs: create
    
    permissions: write-all
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
        
      - uses: actions/download-artifact@v3
        with:
          name: chainsaw.xcframework.zip
          path: ./build/

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          release_name: Release ${{ github.event.inputs.version }}
          tag_name: ${{ github.event.inputs.version }}
          body: This is our release. We should probably have some kind of release notes here but I am lazy.
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload xcframework artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/chainsaw.xcframework.zip
          asset_name: chainsaw.xcframework.zip
          asset_content_type: application/zip
          
  public-release:
      name: Create Public Release
      runs-on: macos-latest
      needs: create
    
      permissions: write-all
  
      steps:
       - name: Checkout
         uses: actions/checkout@v3
         with:
          repository: Zamo22/upgraded-chainsaw
          token: ${{ secrets.PAT_TOKEN }}
          ref: main
        
       - uses: actions/download-artifact@v3
         with:
          name: chainsaw.xcframework.zip
          path: ./build/

      ## This can definitely be improved to use pattern matching instead of the entire line
       - name: Update Package File
         run: |
          CHECKSUM=$(swift package compute-checksum ./build/chainsaw.xcframework.zip)
          CHECKSUMLINE="      checksum: \"${CHECKSUM}\"" 
          URL="      url: \"https:\/\/github.com\/Zamo22\/upgraded-chainsaw\/releases\/download\/${{ github.event.inputs.version }}\/chainsaw.xcframework.zip\","
          sed -i '' "19s/.*/$URL/" "./Package.swift"
          sed -i '' "20s/.*/$CHECKSUMLINE/" "./Package.swift"
          
       - name: Commit package file changes
         uses: EndBug/add-and-commit@v9
         with:
          author_name: Zamo22
          author_email: zmoola22@gmail.com
          message: 'Updating Package file for release'
          add: 'Package.swift'
          tag: '${{ github.event.inputs.version }}'
          
       - name: Release to public repo
         uses: softprops/action-gh-release@v1
         with:
           repository: Zamo22/upgraded-chainsaw
           token: ${{ secrets.PAT_TOKEN }}
           tag_name: ${{ github.event.inputs.version }}
           files: ./build/chainsaw.xcframework.zip
