name: Release Framework

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Version of the Release


jobs:
  build:
    name: Create XCFramework
    runs-on: macos-latest

    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Archive Different Environments
        run: |
          xcodebuild archive -scheme "fantastic-chainsaw" -destination 'generic/platform=iOS Simulator' -archivePath './build/fantastic-chainsaw.framework-iphoneos.xcarchive'
          xcodebuild archive -scheme "fantastic-chainsaw" -destination 'generic/platform=iOS' -archivePath './build/fantastic-chainsaw.framework-iphonesimulator.xcarchive'
          xcodebuild archive -scheme "fantastic-chainsaw" -destination 'platform=macOS,arch=x86_64,variant=Mac Catalyst' -archivePath './build/fantastic-chainsaw.framework-catalyst.xcarchive'
          
      - name: Generate XCFramework
        run: >
          xcodebuild -create-xcframework
          -framework './build/fantastic-chainsaw.framework-iphonesimulator.xcarchive/Products/Library/Frameworks/fantastic_chainsaw.framework'
          -framework './build/fantastic-chainsaw.framework-iphoneos.xcarchive/Products/Library/Frameworks/fantastic_chainsaw.framework'
          -framework './build/fantastic-chainsaw.framework-catalyst.xcarchive/Products/Library/Frameworks/fantastic_chainsaw.framework'
          -output './build/fantastic-chainsaw.xcframework'
      
      - name: Compress XCFramework
        run: |
          ditto -c -k --sequesterRsrc --keepParent ./build/fantastic-chainsaw.xcframework ./build/fantastic-chainsaw.xcframework.zip
          
      ## This can definitely be improved to use pattern matching instead of the entire line
      - name: Update Package File
        run: |
          CHECKSUM=$(swift package compute-checksum ./build/fantastic-chainsaw.xcframework.zip)
          CHECKSUMLINE="      checksum: \"${CHECKSUM}\"" 
          URL="      url: \"https:\/\/github.com\/Zamo22\/fantastic-chainsaw\/releases\/download\/${{ github.event.inputs.version }}\/fantastic-chainsaw.xcframework.zip\","
          sed -i '' "17s/.*/$URL/" "./Package.swift"
          sed -i '' "18s/.*/$CHECKSUMLINE/" "./Package.swift"
          
      - name: Commit package file changes
        run: |
          git config --global user.name "Zamo22"
          git config --global user.email "zmoola22@gmail.com"
          git add Package.swift
          git commit -m "Updating Package file for release"
          git push

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          release_name: Release ${{ github.event.inputs.version }}
          tag_name: ${{ github.event.inputs.version }}
          body: This is our release. We should probably have some kind of release notes here but I am lazy.
        env:
          GITHUB_TOKEN: ${{ github.token }}
          
      - name: Upload xcframework artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/fantastic-chainsaw.xcframework.zip
          asset_name: fantastic-chainsaw.xcframework.zip
          asset_content_type: application/zip
