name: iOS starter workflow

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    if: github.event.pull_request.merged == true && github.head_ref == `test/hello` 
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
